(() => {
  'use strict';

  window.buildReadonlyGraphHtml = function buildReadonlyGraphHtml(graph) {
    const safeData = JSON.stringify(graph).replace(/</g, '\\u003c');
    const safeRoutingWorkerSource = JSON.stringify(window.GraphRouting?.createWorkerSource?.() || '')
      .replace(/</g, '\\u003c');
    return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <meta name="relationship-graph-format" content="readonly-v1">
  <title>关系图－只读版</title>
  <style>
    :root{color-scheme:light;--bg:#f5f6f8;--surface:#fff;--text:#18202c;--muted:#667085;--border:#d7dce5;--primary:#1f6feb;--resource:#4b9eea;--system:#e8963e;--output:#54ad72;--content:#d765a4;--staff:#8a70d6;--commercial:#42aeb2;font-family:"Microsoft YaHei UI","PingFang SC",system-ui,sans-serif}
    @media(prefers-color-scheme:dark){:root{color-scheme:dark;--bg:#11151b;--surface:#191f28;--text:#eef2f8;--muted:#a9b3c2;--border:#354052;--primary:#78aefa}}
    :root[data-theme=light]{color-scheme:light;--bg:#f5f6f8;--surface:#fff;--text:#18202c;--muted:#667085;--border:#d7dce5;--primary:#1f6feb}
    :root[data-theme=dark]{color-scheme:dark;--bg:#11151b;--surface:#191f28;--text:#eef2f8;--muted:#a9b3c2;--border:#354052;--primary:#78aefa}
    *{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:var(--bg);color:var(--text)}
    button,select{font:inherit}.app{display:grid;grid-template-rows:auto minmax(0,1fr) auto;width:100%;height:100%}
    header{display:flex;flex-wrap:wrap;align-items:center;gap:10px;padding:10px 14px;border-bottom:1px solid var(--border);background:var(--surface)}
    h1{margin:0 16px 0 0;font-size:17px}label{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:12px}
    select,button{min-height:34px;border:1px solid var(--border);border-radius:8px;padding:5px 9px;background:var(--surface);color:var(--text)}
    input[type=checkbox]{width:16px;height:16px;margin:0;accent-color:var(--primary);cursor:pointer}
    button{cursor:pointer}.spacer{flex:1}.canvas{position:relative;min-height:0;overflow:hidden;background:radial-gradient(circle at 1px 1px,color-mix(in srgb,var(--border) 58%,transparent) 1px,transparent 0) 0 0/18px 18px,var(--bg)}
    svg{display:block;width:100%;height:100%;touch-action:none;user-select:none}.detail{padding:10px 14px;border-top:1px solid var(--border);background:var(--surface);font-size:13px}
    .detail strong{margin-right:8px}.detail span{color:var(--muted)}.group{cursor:pointer}.group-box{fill:color-mix(in srgb,var(--surface) 72%,transparent);stroke:var(--border);stroke-width:1.5;stroke-dasharray:8 6}.group.selected .group-box{stroke:var(--primary);stroke-width:3;stroke-dasharray:none}.group.related:not(.selected) .group-box{stroke:var(--output);stroke-width:3;stroke-dasharray:none;filter:drop-shadow(0 3px 7px color-mix(in srgb,var(--output) 28%,transparent))}
    .group-label{fill:var(--muted);font-size:14px;font-weight:650;pointer-events:none}.edge{fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round;opacity:.48}.edge.core,.edge.economy,.edge.tempo{stroke:var(--system)}.edge.growth{stroke:var(--output)}.edge.content{stroke:var(--content)}.edge.staff{stroke:var(--staff)}.edge.commercial{stroke:var(--commercial)}
    .edge.related{opacity:1;stroke-width:3}.edge.dim,.node.dim,.group.dim{opacity:.08}.edge-gap{fill:var(--bg);pointer-events:none}.edge-label{fill:var(--text);paint-order:stroke;stroke:var(--surface);stroke-width:5px;font-size:11px;opacity:0;pointer-events:none}.edge-label.show{opacity:.94}
    .hit{fill:none;stroke:transparent;stroke-width:15;cursor:pointer}.node{cursor:pointer}.node rect{stroke:var(--border);stroke-width:1.5;rx:8;ry:8}.node.resource rect{fill:color-mix(in srgb,var(--resource) 24%,var(--surface))}.node.system rect{fill:color-mix(in srgb,var(--system) 22%,var(--surface))}.node.output rect{fill:color-mix(in srgb,var(--output) 22%,var(--surface));stroke-width:2.5}.node.content rect{fill:color-mix(in srgb,var(--content) 20%,var(--surface))}.node.staff rect{fill:color-mix(in srgb,var(--staff) 21%,var(--surface))}.node.commercial rect{fill:color-mix(in srgb,var(--commercial) 22%,var(--surface))}.node.selected rect{stroke:var(--primary);stroke-width:4}.node.related:not(.selected) rect{stroke:var(--output);stroke-width:3;filter:drop-shadow(0 3px 7px color-mix(in srgb,var(--output) 30%,transparent))}
    .kind{fill:var(--muted);font-size:9.5px}.label{fill:var(--text);font-size:12px;font-weight:650}
    @media(max-width:700px){header{align-items:flex-start}h1{width:100%}.app{grid-template-rows:auto 65vh auto}.detail{max-height:25vh;overflow:auto}}
  </style>
</head>
<body>
  <div class="app">
    <header>
      <h1 id="title">关系图</h1>
      <label>关系视图<select id="category"><option value="all">全部关系</option></select></label>
      <label>方向<select id="direction"><option value="all">上下游全部</option><option value="upstream">只看上游</option><option value="downstream">只看下游</option></select></label>
      <label>层级<select id="depth"><option value="1">一层</option><option value="2">两层</option><option value="3">三层</option></select></label>
      <label><input id="edgeVisibility" type="checkbox" checked>显示连线</label>
      <span class="spacer"></span>
      <button id="zoomOut" type="button">缩小</button><button id="fit" type="button">适合画布</button><button id="zoomIn" type="button">放大</button>
    </header>
    <div class="canvas"><svg id="canvas" viewBox="0 0 1440 1030" role="group" aria-label="关系图"><defs id="defs"></defs><g id="groups"></g><g id="edges"></g><g id="edgeGaps"></g><g id="labels"></g><g id="nodes"></g></svg></div>
    <div class="detail"><strong id="detailName">全部关系</strong><span id="detailBody">点击节点或分组查看完整输入、输出和关联对象。</span></div>
  </div>
  <script id="graphData" type="application/json">${safeData}</script>
  <script>
    (function(){
      'use strict';
      var NS='http://www.w3.org/2000/svg';
      var graph=JSON.parse(document.getElementById('graphData').textContent);
      var routingWorkerSource=${safeRoutingWorkerSource};
      var svg=document.getElementById('canvas'),defs=document.getElementById('defs'),groupLayer=document.getElementById('groups'),edgeLayer=document.getElementById('edges'),edgeGapLayer=document.getElementById('edgeGaps'),labelLayer=document.getElementById('labels'),nodeLayer=document.getElementById('nodes');
      var category=document.getElementById('category'),direction=document.getElementById('direction'),depth=document.getElementById('depth'),edgeVisibility=document.getElementById('edgeVisibility'),detailName=document.getElementById('detailName'),detailBody=document.getElementById('detailBody');
      var kinds={resource:'资源/输入',system:'经营功能',output:'产出/成长',content:'收集内容',staff:'员工能力',commercial:'商业化入口'};
      function nodeType(node){return String(node&&node.type||kinds[node&&node.kind]||'未分类')}
      function compactNodeType(node){var label=nodeType(node);return label.length>16?label.slice(0,15)+'…':label}
      var defaultTypes=[{id:'core',label:'核心操作',color:'#e8963e'},{id:'economy',label:'资源经济',color:'#e8963e'},{id:'tempo',label:'时间节奏',color:'#e8963e'},{id:'growth',label:'成长反馈',color:'#54ad72'},{id:'content',label:'内容收集',color:'#d765a4'},{id:'staff',label:'员工岗位',color:'#8a70d6'},{id:'commercial',label:'商业化',color:'#42aeb2'}];
      var settings=graph.settings||{},relationTypes=Array.isArray(settings.relationTypes)&&settings.relationTypes.length?settings.relationTypes:defaultTypes,views={all:relationTypes.map(function(type){return type.id})},colors={};
      relationTypes.forEach(function(type){colors[type.id]=type.color||'#e8963e';views[type.id]=[type.id];var option=document.createElement('option');option.value=type.id;option.textContent=type.label||type.id;category.appendChild(option)});
      if(settings.theme&&settings.theme!=='system')document.documentElement.dataset.theme=settings.theme;
      Object.keys(settings.colors||{}).forEach(function(key){document.documentElement.style.setProperty('--'+key,settings.colors[key])});
      document.getElementById('title').textContent=graph.meta&&graph.meta.title||'关系图';document.title=(graph.meta&&graph.meta.title||'关系图')+'－只读版';svg.setAttribute('aria-label',graph.meta&&graph.meta.title||'关系图');
      var selected=null,viewport={x:0,y:0,w:Number(graph.meta.canvasWidth)||1440,h:Number(graph.meta.canvasHeight)||1030},pan=null,moved=false,routeCacheKey='',routeCache=new Map(),routeWorker=null,routeRequestId=0;
      function el(tag,attrs){var e=document.createElementNS(NS,tag);Object.keys(attrs||{}).forEach(function(k){e.setAttribute(k,String(attrs[k]));});return e}
      function endpointType(edge,role){var requested=String(edge&&edge[role+'Type']||'').toLowerCase(),id=String(edge&&edge[role]||'');if(requested==='node'||requested==='group')return requested;if(graph.nodes.some(function(n){return n.id===id}))return'node';if(graph.groups.some(function(g){return g.id===id}))return'group';return''}
      function endpointKey(type,id){return type+':'+id}
      function edgeEndpointKey(edge,role){return endpointKey(endpointType(edge,role),edge[role])}
      function parseEndpointKey(key){var index=String(key||'').indexOf(':');return index<1?{type:'',id:''}:{type:key.slice(0,index),id:key.slice(index+1)}}
      function endpointEntity(type,id){return(type==='group'?graph.groups:graph.nodes).find(function(item){return item.id===id})}
      function endpointLabel(type,entity){return(type==='group'?'分组｜':'节点｜')+(entity?entity.label:'未知端点')}
      function routeEdge(edge){return Object.assign({},edge,{source:edgeEndpointKey(edge,'source'),target:edgeEndpointKey(edge,'target')})}
      Object.keys(colors).forEach(function(cat){var m=el('marker',{id:'a-'+cat,viewBox:'0 0 10 10',refX:9,refY:5,markerUnits:'userSpaceOnUse',markerWidth:9,markerHeight:9,orient:'auto-start-reverse'}),p=el('path',{d:'M 0 0 L 10 5 L 0 10 z'});p.style.fill=colors[cat];m.appendChild(p);defs.appendChild(m)});
      function requestRoutes(key,edgeList,map,blockingIds){
        routeCacheKey=key;routeCache=new Map();routeRequestId+=1;var requestId=routeRequestId;
        if(routeWorker){routeWorker.terminate();routeWorker=null}
        if(typeof Worker==='function'&&routingWorkerSource){try{var url=URL.createObjectURL(new Blob([routingWorkerSource],{type:'text/javascript'}));routeWorker=new Worker(url);URL.revokeObjectURL(url);routeWorker.onmessage=function(event){var message=event.data||{};if(message.requestId!==requestId)return;if(message.type==='route-result'){routeCache=new Map(message.result.entries||[]);routeCache.crossingGaps=message.result.crossingGaps||[];routeWorker.terminate();routeWorker=null;render()}};routeWorker.onerror=function(){if(requestId!==routeRequestId)return;routeWorker.terminate();routeWorker=null;setTimeout(function(){routeCache=focusedRoutes(edgeList,map,blockingIds);render()},0)};routeWorker.postMessage({type:'route',requestId:requestId,edges:edgeList,nodes:Array.from(map.values()),blockingNodeIds:Array.from(blockingIds),canvasMeta:graph.meta||{}});return}catch(error){if(routeWorker){routeWorker.terminate();routeWorker=null}}}
        setTimeout(function(){if(requestId!==routeRequestId)return;routeCache=focusedRoutes(edgeList,map,blockingIds);render()},0)
      }
      function split(text){text=String(text||'');if(text.length<=10)return[text];var i=text.lastIndexOf('/',Math.ceil(text.length/2));i=i>1?i+1:Math.ceil(text.length/2);var a=text.slice(0,i),b=text.slice(i);return b.length>10?[a,b.slice(0,Math.ceil(b.length/2)),b.slice(Math.ceil(b.length/2))]:[a,b]}
      function geometry(a,b,i,edge){edge=edge||{};var acx=a.x+a.w/2,acy=a.y+a.h/2,bcx=b.x+b.w/2,bcy=b.y+b.h/2,dx=bcx-acx,dy=bcy-acy,h=Math.abs(dx)/Math.max(1,(a.w+b.w)/2)>=Math.abs(dy)/Math.max(1,(a.h+b.h)/2),sides=['top','right','bottom','left'],ss=sides.includes(edge.sourceSide)?edge.sourceSide:(h?(dx>=0?'right':'left'):(dy>=0?'bottom':'top')),ts=sides.includes(edge.targetSide)?edge.targetSide:(h?(dx>=0?'left':'right'):(dy>=0?'top':'bottom'));function port(n,s){if(s==='top')return{x:n.x+n.w/2,y:n.y};if(s==='bottom')return{x:n.x+n.w/2,y:n.y+n.h};if(s==='left')return{x:n.x,y:n.y+n.h/2};return{x:n.x+n.w,y:n.y+n.h/2}}function vec(s){if(s==='top')return{x:0,y:-1};if(s==='bottom')return{x:0,y:1};if(s==='left')return{x:-1,y:0};return{x:1,y:0}}var start=port(a,ss),end=port(b,ts),sv=vec(ss),tv=vec(ts),distance=Math.hypot(end.x-start.x,end.y-start.y),type=['straight','polyline','curve'].includes(String(edge.lineType||'').toLowerCase())?String(edge.lineType).toLowerCase():'curve';if(type==='straight')return{d:'M '+start.x+' '+start.y+' L '+end.x+' '+end.y,lx:(start.x+end.x)/2,ly:(start.y+end.y)/2};if(type==='polyline'){var stub=Math.max(18,Math.min(34,distance*.18)),so={x:start.x+sv.x*stub,y:start.y+sv.y*stub},eo={x:end.x+tv.x*stub,y:end.y+tv.y*stub},sh=ss==='left'||ss==='right',th=ts==='left'||ts==='right',points;if(sh&&th){var mx=(so.x+eo.x)/2;points=[start,so,{x:mx,y:so.y},{x:mx,y:eo.y},eo,end]}else if(!sh&&!th){var my=(so.y+eo.y)/2;points=[start,so,{x:so.x,y:my},{x:eo.x,y:my},eo,end]}else if(sh)points=[start,so,{x:eo.x,y:so.y},eo,end];else points=[start,so,{x:so.x,y:eo.y},eo,end];points=points.filter(function(p,idx){var prev=points[idx-1];return!prev||Math.hypot(p.x-prev.x,p.y-prev.y)>.1});return{d:points.map(function(p,idx){return(idx?'L ':'M ')+p.x+' '+p.y}).join(' '),lx:(start.x+end.x)/2,ly:(start.y+end.y)/2}}var bend=Math.max(42,Math.min(145,distance*.4)),j=((i%5)-2)*6,nl=Math.max(1,distance),nx=-(end.y-start.y)/nl,ny=(end.x-start.x)/nl,c1={x:start.x+sv.x*bend+nx*j,y:start.y+sv.y*bend+ny*j},c2={x:end.x+tv.x*bend+nx*j,y:end.y+tv.y*bend+ny*j};return{d:'M '+start.x+' '+start.y+' C '+c1.x+' '+c1.y+', '+c2.x+' '+c2.y+', '+end.x+' '+end.y,lx:(start.x+end.x)/2+nx*j,ly:(start.y+end.y)/2+ny*j}}
      function focusedRoutes(edgeList,map,blockingIds){
        var descriptors=[],ports=new Map(),labels=[],result=new Map(),blockingMap=new Map();
        map.forEach(function(node,id){if(blockingIds.has(id))blockingMap.set(id,node)});
        function addPort(node,side,descriptor,role,opposite){
          var key=node.id+':'+side;
          if(!ports.has(key))ports.set(key,[]);
          ports.get(key).push({node:node,side:side,descriptor:descriptor,role:role,opposite:opposite});
        }
        edgeList.forEach(function(edge,order){
          var source=map.get(edge.source),target=map.get(edge.target);
          if(!source||!target)return;
          var sc={x:source.x+source.w/2,y:source.y+source.h/2},tc={x:target.x+target.w/2,y:target.y+target.h/2},dx=tc.x-sc.x,dy=tc.y-sc.y,horizontal=Math.abs(dx)/Math.max(1,(source.w+target.w)/2)>=Math.abs(dy)/Math.max(1,(source.h+target.h)/2),ss=horizontal?(dx>=0?'right':'left'):(dy>=0?'bottom':'top'),ts=horizontal?(dx>=0?'left':'right'):(dy>=0?'top':'bottom'),d={edge:edge,source:source,target:target,sc:sc,tc:tc,horizontal:horizontal,ss:ss,ts:ts,order:order,sp:null,tp:null,load:0};
          descriptors.push(d);
          addPort(source,ss,d,'source',ss==='left'||ss==='right'?tc.y:tc.x);
          addPort(target,ts,d,'target',ts==='left'||ts==='right'?sc.y:sc.x);
        });
        ports.forEach(function(entries){
          entries.sort(function(a,b){return a.opposite-b.opposite||a.descriptor.order-b.descriptor.order});
          entries.forEach(function(entry,index){
            var n=entry.node,side=entry.side,margin=9,point;
            if(side==='left'||side==='right')point={x:side==='left'?n.x:n.x+n.w,y:n.y+margin+Math.max(1,n.h-margin*2)*(index+1)/(entries.length+1)};
            else point={x:n.x+margin+Math.max(1,n.w-margin*2)*(index+1)/(entries.length+1),y:side==='top'?n.y:n.y+n.h};
            if(entry.role==='source')entry.descriptor.sp=point;else entry.descriptor.tp=point;
            entry.descriptor.load+=entries.length;
          });
        });
        descriptors.sort(function(a,b){return b.load-a.load||Math.abs(b.tc.x-b.sc.x)-Math.abs(a.tc.x-a.sc.x)||a.order-b.order});
        var chosen=[];
        function vector(side){if(side==='left')return{x:-1,y:0};if(side==='right')return{x:1,y:0};if(side==='top')return{x:0,y:-1};return{x:0,y:1}}
        function portArrow(port,side){var outward=vector(side),ux=-outward.x,uy=-outward.y,base={x:port.x-ux*8,y:port.y-uy*8},tip={x:port.x+ux,y:port.y+uy},left={x:base.x-uy*5,y:base.y+ux*5},right={x:base.x+uy*5,y:base.y-ux*5};return{tip:tip,left:left,right:right,minX:Math.min(tip.x,left.x,right.x),maxX:Math.max(tip.x,left.x,right.x),minY:Math.min(tip.y,left.y,right.y),maxY:Math.max(tip.y,left.y,right.y)}}
        var reservedArrows=descriptors.map(function(d){return{edgeId:d.edge.id,triangle:portArrow(d.tp,d.ts)}});
        function curveSamples(curve){var list=[];for(var i=0;i<=32;i++){var t=i/32,m=1-t;list.push({x:m*m*m*curve.s.x+3*m*m*t*curve.c1.x+3*m*t*t*curve.c2.x+t*t*t*curve.t.x,y:m*m*m*curve.s.y+3*m*m*t*curve.c1.y+3*m*t*t*curve.c2.y+t*t*t*curve.t.y})}return list}
        function polySamples(points){var list=[points[0]];for(var i=1;i<points.length;i++){var a=points[i-1],b=points[i],steps=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/8));for(var j=1;j<=steps;j++)list.push({x:a.x+(b.x-a.x)*j/steps,y:a.y+(b.y-a.y)*j/steps})}return list}
        function segments(points){var list=[];for(var i=1;i<points.length;i++)list.push({a:points[i-1],b:points[i]});return list}
        function simplify(points){var clean=[];points.forEach(function(p){var last=clean[clean.length-1];if(!last||Math.hypot(last.x-p.x,last.y-p.y)>.1)clean.push(p)});return clean}
        function inside(point,node,padding){return point.x>node.x-padding&&point.x<node.x+node.w+padding&&point.y>node.y-padding&&point.y<node.y+node.h+padding}
        function hitsNode(samples,d){var hit=false;samples.slice(1,-1).forEach(function(point){if(hit)return;blockingMap.forEach(function(node){if(hit)return;var own=node.id===d.source.id||node.id===d.target.id;if(inside(point,node,own?-.5:10))hit=true})});return hit}
        function collinearOverlap(a,b){var ax=a.b.x-a.a.x,ay=a.b.y-a.a.y,bx=b.b.x-b.a.x,by=b.b.y-b.a.y,cross=ax*by-ay*bx;if(Math.abs(cross)>.05)return 0;if(Math.abs((b.a.x-a.a.x)*ay-(b.a.y-a.a.y)*ax)>.5)return 0;var useX=Math.abs(ax)>=Math.abs(ay),a1=useX?a.a.x:a.a.y,a2=useX?a.b.x:a.b.y,b1=useX?b.a.x:b.a.y,b2=useX?b.b.x:b.b.y;return Math.max(0,Math.min(Math.max(a1,a2),Math.max(b1,b2))-Math.max(Math.min(a1,a2),Math.min(b1,b2)))}
        function overlapsLine(candidate){for(var c=0;c<chosen.length;c++){var existing=chosen[c];for(var i=0;i<candidate.segments.length;i++)for(var j=0;j<existing.segments.length;j++)if(collinearOverlap(candidate.segments[i],existing.segments[j])>1)return true}return false}
        function segmentIntersection(a,b){var rx=a.b.x-a.a.x,ry=a.b.y-a.a.y,sx=b.b.x-b.a.x,sy=b.b.y-b.a.y,den=rx*sy-ry*sx;if(Math.abs(den)<.0001)return null;var qx=b.a.x-a.a.x,qy=b.a.y-a.a.y,t=(qx*sy-qy*sx)/den,u=(qx*ry-qy*rx)/den;if(t<-.0001||t>1.0001||u<-.0001||u>1.0001)return null;return{x:a.a.x+t*rx,y:a.a.y+t*ry}}
        function crossingCount(first,second){var points=[];for(var i=0;i<first.segments.length;i++)for(var j=0;j<second.segments.length;j++){var point=segmentIntersection(first.segments[i],second.segments[j]);if(point&&!points.some(function(existing){return Math.hypot(existing.x-point.x,existing.y-point.y)<3})){points.push(point);if(points.length>1)return points.length}}return points.length}
        function intersectionPoints(first,second){var points=[];for(var i=0;i<first.segments.length;i++)for(var j=0;j<second.segments.length;j++){var point=segmentIntersection(first.segments[i],second.segments[j]);if(point&&!points.some(function(existing){return Math.hypot(existing.x-point.x,existing.y-point.y)<3}))points.push(point)}return points}
        function crossesMoreThanOnce(candidate){for(var i=0;i<chosen.length;i++)if(crossingCount(candidate,chosen[i])>1)return true;return false}
        function crossingTotal(candidate){var total=0;chosen.forEach(function(existing){total+=crossingCount(candidate,existing)});return total}
        function pointInTriangle(point,triangle){function sign(a,b,c){return(a.x-c.x)*(b.y-c.y)-(b.x-c.x)*(a.y-c.y)}var a=sign(point,triangle.tip,triangle.left),b=sign(point,triangle.left,triangle.right),c=sign(point,triangle.right,triangle.tip),negative=a<-.01||b<-.01||c<-.01,positive=a>.01||b>.01||c>.01;return!(negative&&positive)}
        function arrowTriangle(route){var tipPoint=route.samples[route.samples.length-1],cursor=tipPoint,basePoint=route.samples[Math.max(0,route.samples.length-2)],remaining=8;for(var i=route.samples.length-2;i>=0;i--){var previous=route.samples[i],length=Math.hypot(cursor.x-previous.x,cursor.y-previous.y);if(length>=remaining&&length>.001){basePoint={x:cursor.x+(previous.x-cursor.x)*remaining/length,y:cursor.y+(previous.y-cursor.y)*remaining/length};break}remaining-=length;cursor=previous;basePoint=previous}var dx=tipPoint.x-basePoint.x,dy=tipPoint.y-basePoint.y,total=Math.hypot(dx,dy)||1,ux=dx/total,uy=dy/total,base={x:tipPoint.x-ux*8,y:tipPoint.y-uy*8},tip={x:tipPoint.x+ux,y:tipPoint.y+uy},left={x:base.x-uy*5,y:base.y+ux*5},right={x:base.x+uy*5,y:base.y-ux*5};return{tip:tip,left:left,right:right,minX:Math.min(tip.x,left.x,right.x),maxX:Math.max(tip.x,left.x,right.x),minY:Math.min(tip.y,left.y,right.y),maxY:Math.max(tip.y,left.y,right.y)}}
        function segmentHitsTriangle(segment,triangle){if(Math.max(segment.a.x,segment.b.x)<triangle.minX-.01||Math.min(segment.a.x,segment.b.x)>triangle.maxX+.01||Math.max(segment.a.y,segment.b.y)<triangle.minY-.01||Math.min(segment.a.y,segment.b.y)>triangle.maxY+.01)return false;if(pointInTriangle(segment.a,triangle)||pointInTriangle(segment.b,triangle))return true;return[[triangle.tip,triangle.left],[triangle.left,triangle.right],[triangle.right,triangle.tip]].some(function(side){return!!segmentIntersection(segment,{a:side[0],b:side[1]})})}
        function arrowConflict(candidate){var arrow=arrowTriangle(candidate);return chosen.some(function(existing){var oldArrow=arrowTriangle(existing);return existing.segments.some(function(segment){return segmentHitsTriangle(segment,arrow)})||candidate.segments.some(function(segment){return segmentHitsTriangle(segment,oldArrow)})})}
        function reservedArrowHit(candidate,d){var bounds=candidate.samples.reduce(function(box,point){box.minX=Math.min(box.minX,point.x);box.maxX=Math.max(box.maxX,point.x);box.minY=Math.min(box.minY,point.y);box.maxY=Math.max(box.maxY,point.y);return box},{minX:Infinity,maxX:-Infinity,minY:Infinity,maxY:-Infinity});return reservedArrows.some(function(reserved){var triangle=reserved.triangle;if(reserved.edgeId===d.edge.id||bounds.maxX<triangle.minX||bounds.minX>triangle.maxX||bounds.maxY<triangle.minY||bounds.minY>triangle.maxY)return false;return candidate.segments.some(function(segment){return segmentHitsTriangle(segment,triangle)})})}
        function crossingPenalty(candidate){var score=0;chosen.forEach(function(existing){var count=crossingCount(candidate,existing);if(count>1)score+=(count-1)*100000;score+=count*100});return score}
        function candidateLength(candidate){var total=0;for(var i=1;i<candidate.samples.length;i++)total+=Math.hypot(candidate.samples[i].x-candidate.samples[i-1].x,candidate.samples[i].y-candidate.samples[i-1].y);return total}
        function routePriority(candidate){return crossingTotal(candidate)*100000+candidateLength(candidate)+(candidate.type==='curve'?0:18)}
        function insideCanvas(candidate){var w=Number(graph.meta.canvasWidth)||1440,h=Number(graph.meta.canvasHeight)||1030;return candidate.samples.every(function(point){return point.x>=4&&point.x<=w-4&&point.y>=4&&point.y<=h-4})}
        function pathData(candidate){if(candidate.type==='curve'){var c=candidate.curve;return'M '+c.s.x+' '+c.s.y+' C '+c.c1.x+' '+c.c1.y+', '+c.c2.x+' '+c.c2.y+', '+c.t.x+' '+c.t.y}var path='M '+candidate.points[0].x+' '+candidate.points[0].y;for(var i=1;i<candidate.points.length;i++)path+=' L '+candidate.points[i].x+' '+candidate.points[i].y;return path}
        function segmentInsideCanvas(a,b){var w=Number(graph.meta.canvasWidth)||1440,h=Number(graph.meta.canvasHeight)||1030;return a.x>=4&&a.x<=w-4&&a.y>=4&&a.y<=h-4&&b.x>=4&&b.x<=w-4&&b.y>=4&&b.y<=h-4}
        function segmentHitsNode(a,b,node,padding){var left=node.x-padding,right=node.x+node.w+padding,top=node.y-padding,bottom=node.y+node.h+padding,dx=b.x-a.x,dy=b.y-a.y,min=0,max=1,clips=[[-dx,a.x-left],[dx,right-a.x],[-dy,a.y-top],[dy,bottom-a.y]];for(var i=0;i<clips.length;i++){var direction=clips[i][0],distance=clips[i][1];if(Math.abs(direction)<.0001){if(distance<0)return false;continue}var ratio=distance/direction;if(direction<0)min=Math.max(min,ratio);else max=Math.min(max,ratio);if(min>max)return false}return true}
        function segmentClear(d,a,b){if(!segmentInsideCanvas(a,b))return false;var blocked=false;blockingMap.forEach(function(node){var own=node.id===d.source.id||node.id===d.target.id;if(!blocked&&segmentHitsNode(a,b,node,own?-.5:10))blocked=true});if(!blocked){var segment={a:a,b:b};blocked=reservedArrows.some(function(reserved){return reserved.edgeId!==d.edge.id&&segmentHitsTriangle(segment,reserved.triangle)})}return!blocked}
        function segmentReusesLine(a,b){var probe={type:'poly',segments:[{a:a,b:b}],samples:polySamples([a,b])};return overlapsLine(probe)||crossesMoreThanOnce(probe)}
        function crossingAware(vertices,d,s,t){
          var cache=new Map(),lists=Array.from({length:vertices.length},function(){return[]}),heap=[];
          function bits(mask){var count=0;for(var value=mask;value;value&=value-1n)count++;return count}
          function info(a,b,key){if(cache.has(key))return cache.get(key);if(!segmentClear(d,a,b)){var blocked={valid:false,mask:0n};cache.set(key,blocked);return blocked}var probe={samples:[a,b],segments:[{a:a,b:b}]};if(overlapsLine(probe)){var overlap={valid:false,mask:0n};cache.set(key,overlap);return overlap}var mask=0n;for(var i=0;i<chosen.length;i++){var count=crossingCount(probe,chosen[i]);if(count>1){var multiple={valid:false,mask:0n};cache.set(key,multiple);return multiple}if(count===1)mask|=1n<<BigInt(i)}var result={valid:true,mask:mask};cache.set(key,result);return result}
          function push(state){heap.push(state);var index=heap.length-1;while(index>0){var parent=Math.floor((index-1)/2);if(heap[parent].cost<=state.cost)break;heap[index]=heap[parent];index=parent}heap[index]=state}
          function pop(){var first=heap[0],last=heap.pop();if(heap.length&&last){var index=0;while(true){var child=index*2+1;if(child>=heap.length)break;if(child+1<heap.length&&heap[child+1].cost<heap[child].cost)child++;if(heap[child].cost>=last.cost)break;heap[index]=heap[child];index=child}heap[index]=last}return first}
          function add(state){var list=lists[state.vertex];if(list.some(function(old){return old.active&&old.cost<=state.cost&&(old.mask&state.mask)===old.mask}))return false;list.forEach(function(old){if(old.active&&state.cost<=old.cost&&(state.mask&old.mask)===state.mask)old.active=false});var active=list.filter(function(old){return old.active});if(active.length>=16){active.sort(function(a,b){return a.cost-b.cost});if(active[15].cost<=state.cost)return false;active.slice(15).forEach(function(old){old.active=false})}list.push(state);push(state);return true}
          var prefix=info(s,vertices[0],'prefix'),suffix=info(vertices[1],t,'suffix');if(!prefix.valid||!suffix.valid||(prefix.mask&suffix.mask)!==0n)return null;add({vertex:0,mask:prefix.mask,cost:bits(prefix.mask)*2500+Math.hypot(vertices[0].x-s.x,vertices[0].y-s.y),previous:null,active:true});var explored=0;
          while(heap.length&&explored<12000){var state=pop();if(!state||!state.active)continue;explored++;if(state.vertex===1){var middle=[];for(var cursor=state;cursor;cursor=cursor.previous)middle.push(vertices[cursor.vertex]);middle.reverse();var points=simplify([s].concat(middle,[t])),samples=polySamples(points),candidate={type:'poly',points:points,samples:samples,segments:segments(points)};if(!hitsNode(samples,d)&&!reservedArrowHit(candidate,d)&&!overlapsLine(candidate)&&!crossesMoreThanOnce(candidate)&&!arrowConflict(candidate))return candidate;continue}for(var next=0;next<vertices.length;next++){if(next===state.vertex)continue;var low=Math.min(state.vertex,next),high=Math.max(state.vertex,next),transition=info(vertices[state.vertex],vertices[next],low+':'+high);if(!transition.valid||(state.mask&transition.mask)!==0n)continue;var combined=state.mask|transition.mask,length=Math.hypot(vertices[next].x-vertices[state.vertex].x,vertices[next].y-vertices[state.vertex].y);if(next===1){if((combined&suffix.mask)!==0n)continue;combined|=suffix.mask;length+=Math.hypot(t.x-vertices[1].x,t.y-vertices[1].y)}add({vertex:next,mask:combined,cost:state.cost+(bits(combined)-bits(state.mask))*2500+length+(state.previous?10:0),previous:state,active:true})}}
          return null
        }
        function visibilityRoute(d,s,t,sOut,tOut){var w=Number(graph.meta.canvasWidth)||1440,h=Number(graph.meta.canvasHeight)||1030,vertices=[sOut,tOut];blockingMap.forEach(function(node){var left=Math.max(6,node.x-12),right=Math.min(w-6,node.x+node.w+12),top=Math.max(6,node.y-12),bottom=Math.min(h-6,node.y+node.h+12);vertices.push({x:left,y:top},{x:right,y:top},{x:right,y:bottom},{x:left,y:bottom})});var canvasVertices=[{x:6,y:6},{x:w-6,y:6},{x:w-6,y:h-6},{x:6,y:h-6}],awareVertices=vertices.concat(canvasVertices);vertices.push.apply(vertices,canvasVertices);var count=vertices.length,dist=new Array(count).fill(Infinity),previous=new Array(count).fill(-1),visited=new Array(count).fill(false);dist[0]=0;for(var turn=0;turn<count;turn++){var current=-1;for(var i=0;i<count;i++)if(!visited[i]&&(current<0||dist[i]<dist[current]))current=i;if(current<0||!isFinite(dist[current])||current===1)break;visited[current]=true;for(var next=0;next<count;next++){if(next===current||visited[next])continue;var a=vertices[current],b=vertices[next];if(!segmentClear(d,a,b)||segmentReusesLine(a,b))continue;var probeSamples=polySamples([a,b]),probe={samples:probeSamples,segments:segments(probeSamples)},length=Math.hypot(b.x-a.x,b.y-a.y),bend=previous[current]<0?0:10,score=dist[current]+crossingTotal(probe)*2500+length+bend;if(score<dist[next]){dist[next]=score;previous[next]=current}}}if(!isFinite(dist[1]))return null;var route=[],cursor=1;while(cursor>=0){route.push(vertices[cursor]);cursor=previous[cursor]}route.reverse();var points=simplify([s].concat(route,[t])),candidate={type:'poly',points:points,samples:polySamples(points),segments:segments(points)},nodeHit=hitsNode(candidate.samples,d),reservedHit=reservedArrowHit(candidate,d),overlap=overlapsLine(candidate),multiple=crossesMoreThanOnce(candidate),arrow=arrowConflict(candidate);if(!nodeHit&&!reservedHit&&!overlap&&multiple&&!arrow){var aware=crossingAware(awareVertices,d,s,t);if(aware)return aware}return nodeHit||reservedHit||overlap||multiple||arrow?null:candidate}
        descriptors.forEach(function(d){
          var s=d.sp,t=d.tp,sv=vector(d.ss),tv=vector(d.ts),distance=Math.hypot(t.x-s.x,t.y-s.y)||1,normal={x:-(t.y-s.y)/distance,y:(t.x-s.x)/distance},delta={x:t.x-s.x,y:t.y-s.y},sOut={x:s.x+sv.x*8,y:s.y+sv.y*8},tOut={x:t.x+tv.x*8,y:t.y+tv.y*8},candidates=[];
          [.26,.38].forEach(function(ratio){[10,-10,20,-20,38,-38,64,-64,96,-96,140,-140,200,-200,280,-280,360,-360,480,-480].forEach(function(bow){var curve={s:s,c1:{x:s.x+delta.x*ratio+normal.x*bow,y:s.y+delta.y*ratio+normal.y*bow},c2:{x:t.x-delta.x*ratio+normal.x*bow,y:t.y-delta.y*ratio+normal.y*bow},t:t},samples=curveSamples(curve);candidates.push({type:'curve',curve:curve,samples:samples,segments:segments(samples)})})});[Math.max(46,Math.min(190,distance*.38)),Math.max(70,Math.min(250,distance*.55)),Math.max(34,Math.min(130,distance*.27))].forEach(function(handle){[0,28,-28,56,-56,92,-92,132,-132,190,-190,260,-260,340,-340,440,-440].forEach(function(bow){var curve={s:s,c1:{x:s.x+sv.x*handle+normal.x*bow,y:s.y+sv.y*handle+normal.y*bow},c2:{x:t.x+tv.x*handle+normal.x*bow,y:t.y+tv.y*handle+normal.y*bow},t:t},samples=curveSamples(curve);candidates.push({type:'curve',curve:curve,samples:samples,segments:segments(samples)})})});
          var xLanes=[6,(Number(graph.meta.canvasWidth)||1440)-6,(sOut.x+tOut.x)/2],yLanes=[6,(Number(graph.meta.canvasHeight)||1030)-6,(sOut.y+tOut.y)/2];blockingMap.forEach(function(node){xLanes.push(node.x-16,node.x+node.w+16);yLanes.push(node.y-16,node.y+node.h+16)});var centerX=(sOut.x+tOut.x)/2,centerY=(sOut.y+tOut.y)/2,compactX=Array.from(new Set(xLanes.map(Math.round))).sort(function(a,b){return Math.abs(a-centerX)-Math.abs(b-centerX)}).slice(0,15),compactY=Array.from(new Set(yLanes.map(Math.round))).sort(function(a,b){return Math.abs(a-centerY)-Math.abs(b-centerY)}).slice(0,15);
          var polyLists=[[s,sOut,tOut,t]];compactX.forEach(function(x){polyLists.push([s,sOut,{x:x,y:sOut.y},{x:x,y:tOut.y},tOut,t])});compactY.forEach(function(y){polyLists.push([s,sOut,{x:sOut.x,y:y},{x:tOut.x,y:y},tOut,t])});polyLists.forEach(function(points){points=simplify(points);var samples=polySamples(points);candidates.push({type:'poly',points:points,samples:samples,segments:segments(points)})});
          function usable(candidate){return insideCanvas(candidate)&&!hitsNode(candidate.samples,d)&&!reservedArrowHit(candidate,d)&&!overlapsLine(candidate)&&!crossesMoreThanOnce(candidate)&&!arrowConflict(candidate)}
          var valid=candidates.filter(usable),extended=[];
          if(!valid.some(function(candidate){return crossingTotal(candidate)===0})){
            compactX.forEach(function(x){compactY.forEach(function(y){[[s,sOut,{x:x,y:sOut.y},{x:x,y:y},{x:tOut.x,y:y},tOut,t],[s,sOut,{x:sOut.x,y:y},{x:x,y:y},{x:x,y:tOut.y},tOut,t]].forEach(function(points){points=simplify(points);var samples=polySamples(points);extended.push({type:'poly',points:points,samples:samples,segments:segments(points)})})})});
            valid=valid.concat(extended.filter(usable));
          }
          valid.sort(function(a,b){return routePriority(a)-routePriority(b)});
          var selectedRoute=valid[0];
          if(!selectedRoute||crossingTotal(selectedRoute)>0){var visibility=visibilityRoute(d,s,t,sOut,tOut);if(visibility&&(!selectedRoute||routePriority(visibility)<routePriority(selectedRoute)))selectedRoute=visibility}
          if(!selectedRoute){console.warn('无法在画布内为关系生成避开节点的路径：'+d.edge.id);return}selectedRoute.edgeId=d.edge.id;chosen.push(selectedRoute);
          var width=Math.max(48,Math.min(190,String(d.edge.label||'').length*11+18)),label=null,labelScore=Infinity,routeSamples=selectedRoute.samples,sampleIndexes=[.5,.38,.62,.28,.72].map(function(r){return Math.max(1,Math.min(routeSamples.length-2,Math.round((routeSamples.length-1)*r)))});sampleIndexes.forEach(function(sampleIndex,rank){var point=routeSamples[sampleIndex],before=routeSamples[sampleIndex-1],after=routeSamples[sampleIndex+1],length=Math.hypot(after.x-before.x,after.y-before.y)||1,nx=-(after.y-before.y)/length,ny=(after.x-before.x)/length;[-1,1].forEach(function(side){var x=point.x+nx*side*16,y=point.y+ny*side*16+4,box={x:x-width/2,y:y-14,w:width,h:20},score=rank;labels.forEach(function(existing){if(box.x<existing.x+existing.w&&box.x+box.w>existing.x&&box.y<existing.y+existing.h&&box.y+box.h>existing.y)score+=1200});map.forEach(function(node){if(box.x<node.x+node.w+5&&box.x+box.w>node.x-5&&box.y<node.y+node.h+5&&box.y+box.h>node.y-5)score+=620});if(score<labelScore){labelScore=score;label={x:x,y:y,box:box}}})});labels.push(label.box);result.set(d.edge.id,{d:pathData(selectedRoute),lx:label.x,ly:label.y});
        });
        var crossingGaps=[];for(var first=0;first<chosen.length;first++)for(var second=first+1;second<chosen.length;second++){var crossings=intersectionPoints(chosen[first],chosen[second]);crossings.slice(1).forEach(function(point){if(!crossingGaps.some(function(existing){return Math.hypot(existing.x-point.x,existing.y-point.y)<3}))crossingGaps.push(point)})}result.crossingGaps=crossingGaps;return result;
      }
      function focusSet(visible){var n=new Set(),e=new Set();if(!selected)return{nodes:n,edges:e,active:false};n.add(selected);var q=[{id:selected,l:0}],qi=0,seen=new Map([[selected,0]]),max=Number(depth.value)||1,dir=direction.value,adjacent=new Map();function add(from,to,edgeId){if(!adjacent.has(from))adjacent.set(from,[]);adjacent.get(from).push({id:to,edgeId:edgeId})}graph.edges.forEach(function(edge){if(!visible.has(edge.category))return;var source=edgeEndpointKey(edge,'source'),target=edgeEndpointKey(edge,'target');if(dir==='all'||dir==='downstream')add(source,target,edge.id);if(dir==='all'||dir==='upstream')add(target,source,edge.id)});while(qi<q.length){var cur=q[qi++];if(cur.l>=max)continue;(adjacent.get(cur.id)||[]).forEach(function(neighbor){e.add(neighbor.edgeId);n.add(neighbor.id);var nl=cur.l+1;if(!seen.has(neighbor.id)||seen.get(neighbor.id)>nl){seen.set(neighbor.id,nl);q.push({id:neighbor.id,l:nl})}})}return{nodes:n,edges:e,active:true}}
      function render(){svg.setAttribute('viewBox',viewport.x+' '+viewport.y+' '+viewport.w+' '+viewport.h);groupLayer.replaceChildren();edgeLayer.replaceChildren();edgeGapLayer.replaceChildren();labelLayer.replaceChildren();nodeLayer.replaceChildren();var visible=new Set(views[category.value]||views.all),focus=focusSet(visible),map=new Map(),participating=new Set();graph.edges.forEach(function(edge){if(!visible.has(edge.category))return;participating.add(edgeEndpointKey(edge,'source'));participating.add(edgeEndpointKey(edge,'target'))});graph.nodes.forEach(function(n){var key=endpointKey('node',n.id);map.set(key,Object.assign({},n,{id:key,_type:'node'}))});graph.groups.forEach(function(g){var key=endpointKey('group',g.id);map.set(key,Object.assign({},g,{id:key,_type:'group'}))});
        graph.groups.forEach(function(g){var key=endpointKey('group',g.id),participates=participating.has(key),related=focus.active&&focus.nodes.has(key)&&selected!==key,dim=category.value!=='all'&&!participates||focus.active&&!focus.nodes.has(key),wrapper=el('g',{class:'group'+(selected===key?' selected':'')+(related?' related':'')+(dim?' dim':''),tabindex:0,role:'button','aria-label':'分组：'+g.label}),r=el('rect',{class:'group-box',x:g.x,y:g.y,width:g.w,height:g.h,rx:12}),t=el('text',{class:'group-label',x:g.x+12,y:g.y+23});t.textContent=g.label;wrapper.append(r,t);function chooseGroup(ev){ev.stopPropagation();selected=key;showDetail(key);render()}wrapper.addEventListener('click',chooseGroup);wrapper.addEventListener('keydown',function(ev){if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();chooseGroup(ev)}});groupLayer.appendChild(wrapper)});
        var routeKey=[selected,category.value,direction.value,depth.value,Array.from(focus.nodes).join(','),Array.from(focus.edges).join(',')].join('|'),routes;if(focus.active){if(routeCacheKey!==routeKey){requestRoutes(routeKey,graph.edges.filter(function(edge){return focus.edges.has(edge.id)&&visible.has(edge.category)}).map(routeEdge),map,focus.nodes)}routes=routeCache}else{routeRequestId+=1;if(routeWorker){routeWorker.terminate();routeWorker=null}routes=new Map()}var edgeIndex=new Map(graph.edges.map(function(edge,index){return[edge.id,index]})),renderEdges=focus.active?graph.edges.filter(function(edge){return focus.edges.has(edge.id)}):graph.edges;
        renderEdges.forEach(function(edge){var sourceKey=edgeEndpointKey(edge,'source'),targetKey=edgeEndpointKey(edge,'target'),a=map.get(sourceKey),b=map.get(targetKey);if(!a||!b)return;var rel=focus.edges.has(edge.id);if(!edgeVisibility.checked&&(!focus.active||!rel))return;var focusedGeo=routes.get(edge.id),geo=focusedGeo||geometry(a,b,edgeIndex.get(edge.id)||0,edge),dim=!visible.has(edge.category)||(focus.active&&!rel),p=el('path',{class:'edge '+edge.category+(rel?' related':'')+(dim?' dim':''),d:geo.d,'marker-end':'url(#a-'+edge.category+')'}),hit=el('path',{class:'hit',d:geo.d,tabindex:0,role:'button','aria-label':edge.label?'关系：'+edge.label:'关系：'+endpointLabel(a._type,a)+' 到 '+endpointLabel(b._type,b)}),lab=el('text',{class:'edge-label'+(focus.active&&rel?' show':''),x:geo.lx,y:geo.ly,'text-anchor':'middle'});p.style.stroke=colors[edge.category]||'#e8963e';lab.textContent=edge.label;function chooseEdge(ev){ev.stopPropagation();selected=sourceKey;showDetail(sourceKey);render()}hit.addEventListener('click',chooseEdge);hit.addEventListener('keydown',function(ev){if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();chooseEdge(ev)}});edgeLayer.append(p,hit);if(edge.label)labelLayer.appendChild(lab)});(routes.crossingGaps||[]).forEach(function(point){edgeGapLayer.appendChild(el('circle',{class:'edge-gap',cx:point.x,cy:point.y,r:4.5}))});
        graph.nodes.forEach(function(node){var key=endpointKey('node',node.id),participates=participating.has(key),related=focus.active&&focus.nodes.has(key)&&selected!==key,dim=category.value!=='all'&&!participates||focus.active&&!focus.nodes.has(key),g=el('g',{class:'node '+node.kind+(key===selected?' selected':'')+(related?' related':'')+(dim?' dim':''),tabindex:0,role:'button','aria-label':'节点：'+node.label+'，类型：'+nodeType(node)}),r=el('rect',{x:node.x,y:node.y,width:node.w,height:node.h}),k=el('text',{class:'kind',x:node.x+10,y:node.y+15});k.textContent=compactNodeType(node);g.append(r,k);var lines=split(node.label),base=node.y+(lines.length===1?node.h/2+10:node.h/2+2-(lines.length-2)*7);lines.forEach(function(line,idx){var t=el('text',{class:'label',x:node.x+node.w/2,y:base+idx*15,'text-anchor':'middle'});t.textContent=line;g.appendChild(t)});function chooseNode(ev){ev.stopPropagation();selected=key;showDetail(key);render()}g.addEventListener('click',chooseNode);g.addEventListener('keydown',function(ev){if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();chooseNode(ev)}});nodeLayer.appendChild(g)})}
      function showDetail(key){var parsed=parseEndpointKey(key),entity=endpointEntity(parsed.type,parsed.id);if(!entity)return;var incoming=graph.edges.filter(function(e){return edgeEndpointKey(e,'target')===key}),outgoing=graph.edges.filter(function(e){return edgeEndpointKey(e,'source')===key});function relationText(edge,role){var otherKey=edgeEndpointKey(edge,role),other=parseEndpointKey(otherKey),otherEntity=endpointEntity(other.type,other.id);return endpointLabel(other.type,otherEntity)+(edge.label?'（'+edge.label+'）':'')}detailName.textContent=endpointLabel(parsed.type,entity)+(parsed.type==='node'?'｜'+nodeType(entity):'');detailBody.textContent=(parsed.type==='node'?(entity.note||'暂无说明。'):'分组关系')+' 输入：'+(incoming.length?incoming.map(function(e){return relationText(e,'source')}).join('、'):'无')+'。输出：'+(outgoing.length?outgoing.map(function(e){return relationText(e,'target')}).join('、'):'无')+'。'}
      function point(ev){var r=svg.getBoundingClientRect();return{x:viewport.x+(ev.clientX-r.left)/r.width*viewport.w,y:viewport.y+(ev.clientY-r.top)/r.height*viewport.h}}
      function zoom(f,c){c=c||{x:viewport.x+viewport.w/2,y:viewport.y+viewport.h/2};var nw=Math.max(360,Math.min((graph.meta.canvasWidth||1440)*2.4,viewport.w*f)),nh=nw*(viewport.h/viewport.w),rx=(c.x-viewport.x)/viewport.w,ry=(c.y-viewport.y)/viewport.h;viewport.x=c.x-nw*rx;viewport.y=c.y-nh*ry;viewport.w=nw;viewport.h=nh;render()}
      category.addEventListener('change',render);direction.addEventListener('change',render);depth.addEventListener('change',render);edgeVisibility.addEventListener('change',render);document.getElementById('zoomOut').addEventListener('click',function(){zoom(1.22)});document.getElementById('zoomIn').addEventListener('click',function(){zoom(.82)});document.getElementById('fit').addEventListener('click',function(){viewport={x:0,y:0,w:Number(graph.meta.canvasWidth)||1440,h:Number(graph.meta.canvasHeight)||1030};render()});
      document.addEventListener('contextmenu',function(ev){ev.preventDefault()});document.addEventListener('auxclick',function(ev){if(ev.button===2)ev.preventDefault()});svg.addEventListener('wheel',function(ev){ev.preventDefault();zoom(ev.deltaY<0?.88:1.14,point(ev))},{passive:false});svg.addEventListener('pointerdown',function(ev){if(ev.button!==0||ev.isPrimary===false||ev.target.closest('.node')||ev.target.closest('.group')||ev.target.closest('.hit'))return;pan={id:ev.pointerId,x:ev.clientX,y:ev.clientY,vx:viewport.x,vy:viewport.y};moved=false});window.addEventListener('pointermove',function(ev){if(!pan||pan.id!==ev.pointerId)return;var r=svg.getBoundingClientRect(),dx=(ev.clientX-pan.x)/r.width*viewport.w,dy=(ev.clientY-pan.y)/r.height*viewport.h;viewport.x=pan.vx-dx;viewport.y=pan.vy-dy;moved=Math.abs(dx)>1||Math.abs(dy)>1;render()});window.addEventListener('pointerup',function(ev){if(pan&&pan.id===ev.pointerId){pan=null;setTimeout(function(){moved=false},0)}});svg.addEventListener('click',function(ev){if(moved||ev.target.closest('.node')||ev.target.closest('.group')||ev.target.closest('.hit'))return;selected=null;detailName.textContent='全部关系';detailBody.textContent='点击节点或分组查看完整输入、输出和关联对象。';render()});
      render();
    })();
  </script>
</body>
</html>`;
  };
})();
